apiVersion: apps/v1beta2

kind: Deployment

metadata:

  name: hello-world-dp

spec:

  replicas: 3
  minReadySeconds: 3

  selector:

    app: hello-world

  template:

    metadata:

      name: hello-world-pod

      labels:

        app: hello-world

    spec:

      containers:

      - name: hello-world

        image: docker.io/kimo11131/hello-world:v1

        imagePullPolicy: Always

        ports:

        - containerPort: 8080